// Generated by CoffeeScript 1.9.2
var Fluxxor, TodoStore, actions, flux, stores;

Fluxxor = require('fluxxor');

actions = require('../actions/todo-actions');

TodoStore = require('../stores/todo-store');

stores = {
  'TodoStore': new TodoStore()
};

flux = new Fluxxor.Flux(stores, actions);

flux.on('dispatch', function(type, payload) {});

module.exports = flux;
